apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
    - name: amqps
      protocol: TCP
      port: 5671
      nodePort: 30000
    - name: rabbitmq-management-https
      protocol: TCP
      port: 15671
      nodePort: 30001
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8.11-management-alpine
        volumeMounts:
          - name: config
            mountPath: /etc/rabbitmq
            readOnly: true
          - name: tls
            mountPath: "/etc/tls"
            readOnly: true
        env:
          # This was something I had to do to get rabbitmqctl to work when using TLS...
          - name: RABBITMQ_CTL_ERL_ARGS
            value: "-proto_dist inet_tls"
        ports:
        - containerPort: 5671
        - containerPort: 15671
      # add liveness check or use higher level controller
      volumes:
        - name: config
          secret:
            secretName: rabbitmq-config-secret
        - name: tls
          secret:
            secretName: rabbitmq-tls-secret
# TODO fix volume claims
